bg_color:            "#17191e"
text_color:          "#d4e5f7"
accent_color:        "#1ebce8"
neutral_color:       "#37393e"
neutral_light_color: "#90949d"

bar_left: |
  <ModuleRow> 
    <Workspaces />
    <Volume />
  </ModuleRow>

bar_center: |
  <ModuleRow>
    <DateTime />
  </ModuleRow>

bar_right: |
  <ModuleRow>
    <Weather ApiKey="0da6062cc70c39e1bbc445580b1db222" Location="Brisbane, AU" />
    <Interface Iface="enp4s0" />
    <CPU />
    <RAM />
    <DiskUsage MountPoint="/" />
  </ModuleRow>
